### PR TITLE
created 3 new wagons

### PR DESCRIPTION
**Pull request by IzzyIllari**
ep2gamma wagon
ep6gamma wagon
epPipPim2Gamma wagon
searching for eta events

### CODE REVIEW

**Comment by gavalian** [comment]
It is generally very bad idea to name classes in Java with lower case.
This can be a problem on some platforms.

**Comment by gavalian** [comment]
Since the code contains comments // Ask about this notation
The notation is a convenient was of combining several particles in one loop without need of "if" statement. For example:

Particle get(Particle[] p, int[] signs){
  Particle r = new Particle();
  for(int i = 0; i < p.length; i++) r.combine(p[i],signs[i]);
  return r;
}

**Comment by IzzyIllari** [comment]
> It is generally very bad idea to name classes in Java with lower case.
> This can be a problem on some platforms.

Would it be sufficient to change the class names to be in all capital letters?

> Since the code contains comments // Ask about this notation
> The notation is a convenient was of combining several particles in one loop without need of "if" statement. For example:
> 
> Particle get(Particle[] p, int[] signs){
> Particle r = new Particle();
> for(int i = 0; i < p.length; i++) r.combine(p[i],signs[i]);
> return r;
> }

Thank you for the information. I can remove those comments.

**Comment by gavalian** [comment]
There are no strict rules, Java suggests naming classes with first letter being Capital Letter. You can change the names to Ep2gamma or something like that, your choice.

**Comment by IzzyIllari** [comment]
> There are no strict rules, Java suggests naming classes with first letter being Capital Letter. You can change the names to Ep2gamma or something like that, your choice.

Ok, I have changed the class names and removed the comments. From my end it appears that these commits have been added. Please let me know if I need to make any other changes or if these changes are not showing up for you.

**Comment by gavalian** [comment]
OK, the name changes worked. All merged.

**Pull request merged**
